language: ruby
rvm:
  - 2.2.7

before_script:
  - chmod +x ./scripts/build.sh
  - chmod +x ./scripts/deploy.sh

script: ./scripts/build.sh

after_success:
  - ./scripts/deploy.sh

branches:
  only:
    - master

sudo: false
